// Generated by CoffeeScript 1.10.0
(function() {
  var SQSQueue, assert, queue;

  assert = require('assert');

  SQSQueue = require('../index');

  queue = new SQSQueue({
    QueueUrl: process.env.QUEUE_URL,
    accessKeyId: process.env.ACCESS_KEY_ID,
    secretAccessKey: process.env.SECRET_ACCESS_KEY
  });

  describe('test', function() {
    return it('should push and retreive data from queue', function(done) {
      var value;
      value = 'hello world';
      queue.createWorker(function(message, _done) {
        _done();
        assert.equal(message.value, value);
        return done();
      });
      return queue.push({
        value: value
      })["catch"](done);
    });
  });

}).call(this);
