// Generated by CoffeeScript 1.10.0
(function() {
  var SQSQueue, assert, queue;

  assert = require('assert');

  SQSQueue = require('../index');

  queue = new SQSQueue({
    QueueUrl: 'https://sqs.eu-central-1.amazonaws.com/458470902217/sqs-queue-test',
    accessKeyId: "AKIAJBR4RCFU5DMYFQFQ",
    secretAccessKey: "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"
  });

  describe('test', function() {
    return it('should push and retreive data from queue', function(done) {
      var value;
      value = 'hello world';
      queue.createWorker(function(message, _done) {
        assert.equal(message.value, value);
        _done();
        return done();
      });
      return queue.push({
        value: value
      })["catch"](done);
    });
  });

}).call(this);
