// Generated by CoffeeScript 1.10.0
(function() {
  var Consumer, Worker;

  Consumer = require('sqs-consumer');

  Worker = (function() {
    Worker.prototype.consumers = [];

    function Worker(options, fn) {
      var consumer, i, j, ref;
      this.options = options;
      for (i = j = 0, ref = this.options.concurrency; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
        consumer = Consumer.create({
          queueUrl: this.options.QueueUrl,
          sqs: this.options.sqs,
          handleMessage: function(message, done) {
            return fn(JSON.parse(message.Body), done);
          }
        });
        this.consumers.push(consumer);
      }
      this.start();
    }

    Worker.prototype.start = function() {
      var consumer, j, len, ref, results;
      ref = this.consumers;
      results = [];
      for (j = 0, len = ref.length; j < len; j++) {
        consumer = ref[j];
        results.push(consumer.start());
      }
      return results;
    };

    Worker.prototype.stop = function() {
      var consumer, j, len, ref, results;
      ref = this.consumers;
      results = [];
      for (j = 0, len = ref.length; j < len; j++) {
        consumer = ref[j];
        results.push(consumer.stop());
      }
      return results;
    };

    return Worker;

  })();

  module.exports = Worker;

}).call(this);
